required <- c("dplyr", "ggplot2", "readr", "tidyr", "patchwork")
missing <- required[!vapply(required, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing)) stop("Missing packages: ", paste(missing, collapse = ", "))
suppressPackageStartupMessages({library(dplyr); library(ggplot2); library(readr); library(tidyr); library(patchwork)})
dir.create("results/tables", recursive = TRUE, showWarnings = FALSE); dir.create("results/figures", recursive = TRUE, showWarnings = FALSE)
anscombe_long <- bind_rows(lapply(1:4, function(i) tibble(set = paste("Set", i), x = anscombe[[paste0("x", i)]], y = anscombe[[paste0("y", i)]])))
anscombe_stats <- anscombe_long %>% group_by(set) %>% summarise(across(c(x,y), list(mean=mean, sd=sd)), correlation=cor(x,y), .groups="drop")
write_csv(anscombe_stats, "results/tables/anscombe_summary.csv")
p_ans <- ggplot(anscombe_long, aes(x,y)) + geom_point(color="#28666E", size=2.2) + geom_smooth(method="lm", se=FALSE, color="#B24C63", linewidth=.7) + facet_wrap(~set, ncol=2) + labs(title="Anscombe's quartet", subtitle="Similar summaries, radically different patterns", caption="Built-in R dataset: anscombe") + theme_minimal(base_size=11)
ipca <- tibble(year=2009:2013, value=c(4.31,5.91,6.50,5.84,5.91))
base_plot <- ggplot(ipca, aes(year,value)) + geom_line(color="#28666E", linewidth=1) + geom_point(color="#28666E", size=2.5) + scale_x_continuous(breaks=ipca$year) + labs(x=NULL,y="Annual index (%)") + theme_minimal(base_size=11)
p_bad <- base_plot + coord_cartesian(ylim=c(4,7)) + labs(title="Truncated scale exaggerates change")
p_good <- base_plot + coord_cartesian(ylim=c(0,7)) + labs(title="Zero baseline restores context")
ggsave("results/figures/anscombe_quartet.png", p_ans, width=8, height=6, dpi=240, bg="white")
ggsave("results/figures/honest_vs_truncated_scale.png", p_bad / p_good + plot_annotation(title="The axis changes the visual claim", caption="Synthetic teaching series; color used consistently and labels provide context."), width=8, height=8, dpi=240, bg="white")
cat("Visualization activities complete: Anscombe, Datasaurus principle, axis integrity, purposeful color, chart choice, complete context.\n")
